-- MySQL Script generated by MySQL Workbench
-- 11/08/15 17:34:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema localtext
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema localtext
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `localtext` DEFAULT CHARACTER SET utf8 ;
USE `localtext` ;

-- -----------------------------------------------------
-- Table `localtext`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`Book` (
  `IDBook` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  `ISBN` BIGINT NULL,
  `PublishYear` INT NULL,
  `Version` INT NULL,
  PRIMARY KEY (`IDBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localtext`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`School` (
  `IDSchool` INT NOT NULL AUTO_INCREMENT,
  `SchoolName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`IDSchool`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localtext`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`User` (
  `IDUser` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NULL,
  `IDSchool` INT NULL,
  PRIMARY KEY (`IDUser`),
  INDEX `IDSchool_idx` (`IDSchool` ASC),
  CONSTRAINT `IDSchool`
    FOREIGN KEY (`IDSchool`)
    REFERENCES `localtext`.`School` (`IDSchool`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localtext`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`Course` (
  `IDCourse` INT NOT NULL AUTO_INCREMENT,
  `CourseCode` VARCHAR(10) NULL,
  `IDSchool` INT NOT NULL,
  PRIMARY KEY (`IDCourse`),
  INDEX `IDSchool_idx` (`IDSchool` ASC),
  CONSTRAINT `IDSchool2`
    FOREIGN KEY (`IDSchool`)
    REFERENCES `localtext`.`School` (`IDSchool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localtext`.`RequiredText`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`RequiredText` (
  `IDBook` INT NOT NULL,
  `IDCourse` INT NOT NULL,
  PRIMARY KEY (`IDBook`, `IDCourse`),
  INDEX `IDCourse_idx` (`IDCourse` ASC),
  CONSTRAINT `IDCourse`
    FOREIGN KEY (`IDCourse`)
    REFERENCES `localtext`.`Course` (`IDCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDBook`
    FOREIGN KEY (`IDBook`)
    REFERENCES `localtext`.`Book` (`IDBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localtext`.`Posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localtext`.`Posting` (
  `IDPosting` INT NOT NULL AUTO_INCREMENT,
  `IDBook` INT NOT NULL,
  `IDUser` INT NOT NULL,
  `IDSchool` INT NULL,
  PRIMARY KEY (`IDPosting`),
  INDEX `IDBook_idx` (`IDBook` ASC),
  INDEX `IDUser_idx` (`IDUser` ASC),
  INDEX `IDSchool_idx` (`IDSchool` ASC),
  CONSTRAINT `IDBook2`
    FOREIGN KEY (`IDBook`)
    REFERENCES `localtext`.`Book` (`IDBook`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `IDUser`
    FOREIGN KEY (`IDUser`)
    REFERENCES `localtext`.`User` (`IDUser`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `IDSchool3`
    FOREIGN KEY (`IDSchool`)
    REFERENCES `localtext`.`School` (`IDSchool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
